version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Cambia esto a una contraseña segura
      MYSQL_DATABASE: parish_register_db        # Cambia esto al nombre de tu base de datos
      MYSQL_USER: admin                  # Cambia esto al nombre de usuario deseado
      MYSQL_PASSWORD: password      # Cambia esto a una contraseña segura
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: